export const products = [
    {
        name: 'Gps64sx',
        price: 1000,
        stock: 8,
        id: '1',
        img: 'https://res.cloudinary.com/buenos-aires/image/upload/v1637706446/gps64sx_ap2rhc.jpg',
        detail: 'GPS de mano con sensores de navegación con múltiples sensores',
        category: 'GPS',
    },
    {
        name: 'Gps65s',
        price: 7000,
        stock: 5,
        id: '2',
        img: 'https://res.cloudinary.com/buenos-aires/image/upload/v1637706446/gps65s_uckm3c.jpg',
        detail: 'Excelente para navegar con embarcaciones pequeñas',
        category: 'GPS',
    },
    {
        name: 'Gps65',
        price: 3500,
        stock: 7,
        id: '3',
        img: 'https://res.cloudinary.com/buenos-aires/image/upload/v1637706446/gps65_ii6bse.jpg',
        detail: 'Sondas SideVü, ClearVü y CHIRP tradicionales con mapa base mundial',
        category: 'GPS',
    },
    {
        name: 'Bronze',
        price: 500,
        stock: 10,
        id: '4',
        img: 'https://res.cloudinary.com/buenos-aires/image/upload/v1637706446/bronzeCarta_wyn1c1.jpg',
        detail: 'South America, Rio de la Plata Inland Maps | Detalles: 60%',
        category: 'CARTAS',
    },
    {
        name: 'Silver',
        price: 700,
        stock: 6,
        id: '5',
        img: 'https://res.cloudinary.com/buenos-aires/image/upload/v1637706446/silverCarta_azqj18.jpg',
        detail: 'South America, East Coast Charts | Detalles: 80%',
        category: 'CARTAS',
    },
    {
        name: 'Gold',
        price: 900,
        stock: 5,
        id: '6',
        img: 'https://res.cloudinary.com/buenos-aires/image/upload/v1637706446/goldCarta_sasvf9.jpg',
        detail: 'South America Coastal Charts | Detalles: 100%',
        category: 'CARTAS',
    },
];
